### ISSUE TITLE
Undergraduate checkbox color

### ISSUE THREAD

**Issue by rafaelgonzalez** [marcom-unimelb/unimelb-design-system#188]
The color of the undergraduate checkbox is a bit too bright:

![screen shot 2015-02-12 at 10 38 53](https://cloud.githubusercontent.com/assets/456921/6158916/7cb276d2-b2a3-11e4-9449-2cd6689ede8e.png)

Might be related to this line? https://github.com/marcom-unimelb/unimelb-design-system/blob/b657549ade734128de846cc6aa75ef4f70554c57/templates/components/filtered-listings/_filters.scss#L92

In the meantime, I have added this fix:

```css
.uomcontent form.filtered-listing-select fieldset.left .undergraduate input[type="checkbox"]+label span::before {
  background-color: #d2f1cf;
}
```
